// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auction.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuction = `-- name: CreateAuction :exec
INSERT INTO auction (
    id, seller_id, title, description, category,
    start_price, min_increment, cap, ends_at, status, created_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11
)
`

type CreateAuctionParams struct {
	ID           pgtype.UUID
	SellerID     pgtype.UUID
	Title        string
	Description  string
	Category     string
	StartPrice   int64
	MinIncrement int64
	Cap          *int64
	EndsAt       pgtype.Timestamptz
	Status       string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateAuction(ctx context.Context, arg CreateAuctionParams) error {
	_, err := q.db.Exec(ctx, createAuction,
		arg.ID,
		arg.SellerID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.StartPrice,
		arg.MinIncrement,
		arg.Cap,
		arg.EndsAt,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const getAuction = `-- name: GetAuction :one
SELECT id, seller_id, title, description, category, start_price, min_increment, cap, ends_at, status, created_at, highest_bid_amount, highest_bidder_id FROM auction WHERE id = $1
`

func (q *Queries) GetAuction(ctx context.Context, id pgtype.UUID) (Auction, error) {
	row := q.db.QueryRow(ctx, getAuction, id)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.StartPrice,
		&i.MinIncrement,
		&i.Cap,
		&i.EndsAt,
		&i.Status,
		&i.CreatedAt,
		&i.HighestBidAmount,
		&i.HighestBidderID,
	)
	return i, err
}

const getAuctionForUpdate = `-- name: GetAuctionForUpdate :one
SELECT id, seller_id, title, description, category, start_price, min_increment, cap, ends_at, status, created_at, highest_bid_amount, highest_bidder_id FROM auction WHERE id = $1 FOR UPDATE
`

// Locks the auction row for the bid transaction. Blocks until the row is free,
// serializing concurrent bids on the same auction into a total order.
func (q *Queries) GetAuctionForUpdate(ctx context.Context, id pgtype.UUID) (Auction, error) {
	row := q.db.QueryRow(ctx, getAuctionForUpdate, id)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.StartPrice,
		&i.MinIncrement,
		&i.Cap,
		&i.EndsAt,
		&i.Status,
		&i.CreatedAt,
		&i.HighestBidAmount,
		&i.HighestBidderID,
	)
	return i, err
}

const listAuctions = `-- name: ListAuctions :many
SELECT id, seller_id, title, description, category, start_price, min_increment, cap, ends_at, status, created_at, highest_bid_amount, highest_bidder_id FROM auction ORDER BY created_at DESC
`

func (q *Queries) ListAuctions(ctx context.Context) ([]Auction, error) {
	rows, err := q.db.Query(ctx, listAuctions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Auction
	for rows.Next() {
		var i Auction
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.StartPrice,
			&i.MinIncrement,
			&i.Cap,
			&i.EndsAt,
			&i.Status,
			&i.CreatedAt,
			&i.HighestBidAmount,
			&i.HighestBidderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuctionHighestBid = `-- name: UpdateAuctionHighestBid :exec
UPDATE auction
SET highest_bid_amount = $2,
    highest_bidder_id  = $3
WHERE id = $1
`

type UpdateAuctionHighestBidParams struct {
	ID               pgtype.UUID
	HighestBidAmount *int64
	HighestBidderID  pgtype.UUID
}

func (q *Queries) UpdateAuctionHighestBid(ctx context.Context, arg UpdateAuctionHighestBidParams) error {
	_, err := q.db.Exec(ctx, updateAuctionHighestBid, arg.ID, arg.HighestBidAmount, arg.HighestBidderID)
	return err
}
