// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bid.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBidsForAuction = `-- name: CountBidsForAuction :one
SELECT count(*) FROM bid WHERE auction_id = $1
`

func (q *Queries) CountBidsForAuction(ctx context.Context, auctionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBidsForAuction, auctionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertBid = `-- name: InsertBid :exec
INSERT INTO bid (id, auction_id, bidder_id, amount, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertBidParams struct {
	ID        pgtype.UUID
	AuctionID pgtype.UUID
	BidderID  pgtype.UUID
	Amount    int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertBid(ctx context.Context, arg InsertBidParams) error {
	_, err := q.db.Exec(ctx, insertBid,
		arg.ID,
		arg.AuctionID,
		arg.BidderID,
		arg.Amount,
		arg.CreatedAt,
	)
	return err
}
