// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Auction struct {
	ID               pgtype.UUID
	SellerID         pgtype.UUID
	Title            string
	Description      string
	Category         string
	StartPrice       int64
	MinIncrement     int64
	Cap              *int64
	EndsAt           pgtype.Timestamptz
	Status           string
	CreatedAt        pgtype.Timestamptz
	HighestBidAmount *int64
	HighestBidderID  pgtype.UUID
}

type Bid struct {
	ID        pgtype.UUID
	AuctionID pgtype.UUID
	BidderID  pgtype.UUID
	Amount    int64
	CreatedAt pgtype.Timestamptz
}
